### ISSUE TITLE
comfyUI_DaVinciResolve install failed: Bad Request

### ISSUE THREAD

**Issue by Amaru-Zeas** [barckley75/comfyUI_DaVinciResolve#4]
comfyUI_DaVinciResolve install failed: Bad Request when trying to install through the manager. If I install it with the github link it does install but nodes wont show up.

**Comment by barckley75** [comment]
Hi @Amaru-Zeas, I didn't even know somebody added it to the manager.

However, In order to use DaVinci node you must have DaVinci Resolve Studio (which is the professional version of DaVinci Resolve) connected to the API.
It works only with DaVinci Resolve Studio and it doesn't work with the free version.

I already added the paths file for MAC in node_text_to_speech which are:

`os.environ["RESOLVE_SCRIPT_API"] = "/Library/Application Support/Blackmagic Design/DaVinci Resolve/Developer/Scripting"`
`os.environ["RESOLVE_SCRIPT_LIB"] = "/Applications/DaVinci Resolve/DaVinci Resolve.app/Contents/Libraries/Fusion/fusionscript.so"`
`sys.path.append(os.path.join(os.environ["RESOLVE_SCRIPT_API"], "Modules"))`
`import DaVinciResolveScript as dvr_script`

so, it should work out of the box if you are using a MAC.

For more information on how to connect the API you can simply find the readme file in DaVinci help:
HELP>DOCUMENTATION>DEVELOPER. It will open a folder, search for scripting folder and then for README.txt file, the API documentation related to the DaVinci version you have installed.

Once your API is running you can  use these nodes:
1. node_text_to_speech.py --> it calls OpenAI API key, refer to OpenAI site for the documentation and prices.
2. save_audio_to_davinci.py --> this node will save the output file in Davinci Resolve Studio.

Hope it helps.

**Comment by Amaru-Zeas** [comment]
Oh Isee, ha maybe someone added it? 

I do have davinci resolve pro and I was able to get the api from you instructions on the readme file, just not sure how to install the nodes in the comfy folder? just do it the old fashion way by pulling it into custom nodes? 

Also I have a windows box, will it work? I have a macbook as well but prefer windows. 

thanks again
